In [89]:
import polars as pl

pl.Config.set_tbl_rows(24)
pl.Config.save()  # saves to ~/.config/polars/config.json

'{"environment":{"POLARS_ENGINE_AFFINITY":null,"POLARS_FMT_MAX_COLS":null,"POLARS_FMT_MAX_ROWS":"24","POLARS_FMT_NUM_DECIMAL":null,"POLARS_FMT_NUM_GROUP_SEPARATOR":null,"POLARS_FMT_NUM_LEN":null,"POLARS_FMT_STR_LEN":null,"POLARS_FMT_TABLE_CELL_ALIGNMENT":null,"POLARS_FMT_TABLE_CELL_LIST_LEN":null,"POLARS_FMT_TABLE_CELL_NUMERIC_ALIGNMENT":null,"POLARS_FMT_TABLE_DATAFRAME_SHAPE_BELOW":null,"POLARS_FMT_TABLE_FORMATTING":null,"POLARS_FMT_TABLE_HIDE_COLUMN_DATA_TYPES":null,"POLARS_FMT_TABLE_HIDE_COLUMN_NAMES":null,"POLARS_FMT_TABLE_HIDE_COLUMN_SEPARATOR":null,"POLARS_FMT_TABLE_HIDE_DATAFRAME_SHAPE_INFORMATION":null,"POLARS_FMT_TABLE_INLINE_COLUMN_DATA_TYPE":null,"POLARS_FMT_TABLE_ROUNDED_CORNERS":null,"POLARS_MAX_EXPR_DEPTH":null,"POLARS_STREAMING_CHUNK_SIZE":null,"POLARS_TABLE_WIDTH":null,"POLARS_VERBOSE":null,"POLARS_WARN_UNSTABLE":null},"direct":{"set_fmt_float":"mixed","set_float_precision":null,"set_thousands_separator":"","set_decimal_separator":".","set_trim_decimal_zeros":false}}'

In [90]:
lf = pl.scan_parquet(
    "../data/raw/yellow_tripdata_2025-01.parquet"
)  # lazy scan - loads on collect()
df = lf.collect()
df.columns = [c.lower() for c in df.columns]
df = df.rename(
    {
        "tpep_pickup_datetime": "pickup_datetime",
        "tpep_dropoff_datetime": "dropoff_datetime",
        "ratecodeid": "rate_code_id",
        "vendorid": "vendor_id",
        "pulocationid": "pickup_location_id",
        "dolocationid": "dropoff_location_id",
    }
)

In [91]:
# Load and join zones data
zones = pl.read_csv("../data/raw/taxi_zone_lookup.csv")
zones.columns = [c.lower() for c in zones.columns]
df = df.join(
    zones.rename({"locationid": "pickup_location_id"}),
    on="pickup_location_id",
    how="left",
)

In [92]:
zones.filter(pl.col("zone").str.contains("Airport"))

shape: (3, 4)
┌────────────┬─────────┬───────────────────┬──────────────┐
│ locationid ┆ borough ┆ zone              ┆ service_zone │
│ ---        ┆ ---     ┆ ---               ┆ ---          │
│ i64        ┆ str     ┆ str               ┆ str          │
╞════════════╪═════════╪═══════════════════╪══════════════╡
│ 1          ┆ EWR     ┆ Newark Airport    ┆ EWR          │
│ 132        ┆ Queens  ┆ JFK Airport       ┆ Airports     │
│ 138        ┆ Queens  ┆ LaGuardia Airport ┆ Airports     │
└────────────┴─────────┴───────────────────┴──────────────┘

In [ ]:
# build is_airport_pickup field
df = df.with_columns(
    pl.col("pickup_location_id").is_in([1, 132, 138]).cast(pl.Int8).alias("is_airport_pickup")
)

In [94]:
# Build model columns
store_and_fwd_bin = {
    "N": 0,
    "Y": 1,
}

df = df.with_columns(
    # Create duration_sec column from dropoff and pickup times
    ((pl.col("dropoff_datetime") - pl.col("pickup_datetime")).dt.total_seconds() / 60).alias(
        "duration_min"
    ),
    # Convert Y/N flagging to 1-hot encoding
    (
        pl.col("store_and_fwd_flag")
        .replace_strict(store_and_fwd_bin, default=None)
        .alias("store_and_fwd_flag")
    ),
)

In [95]:
# %%script echo skipping
# print("This code will be completely ignored.")
# EDA ONLY — drop before modeling
# Build readability columns
vendor_id_map = {
    1: "Creative Mobile Technologies LLC",
    2: "Curb Mobility, LLC",
    6: "Myle Technologies Inc",
    7: "Helix",
}

payment_type_map = {
    0: "flex_fare_trip",
    1: "credit_card",
    2: "cash",
    3: "no_charge",
    4: "dispute",
    5: "unknown",
    6: "voided_trip",
}


rate_code_map = {
    1: "standard_rate",
    2: "jfk",
    3: "newark",
    4: "nassau_or_winchester",
    5: "negotiated_fare",
    6: "group_ride",
    99: "null_or_unknown",
}

df = df.with_columns(
    # Create a new column with readable payment type
    (
        pl.col("payment_type")
        .replace_strict(payment_type_map, default=None)
        .alias("payment_type_str")
    ),
    # Create a new column with readable rate code
    (pl.col("rate_code_id").replace_strict(rate_code_map, default=None).alias("rate_code_str")),
    # Create a new column with readable vendor ID
    (pl.col("vendor_id").replace_strict(vendor_id_map, default=None).alias("vendor_id_str")),
)

In [96]:
# Add avg mph field
df = df.with_columns(
    (pl.col("trip_distance") / (pl.col("duration_min") / 60)).alias("avg_speed_mph")
)

In [97]:
df.schema

Schema([('vendor_id', Int32),
        ('pickup_datetime', Datetime(time_unit='us', time_zone=None)),
        ('dropoff_datetime', Datetime(time_unit='us', time_zone=None)),
        ('passenger_count', Int64),
        ('trip_distance', Float64),
        ('rate_code_id', Int64),
        ('store_and_fwd_flag', Int64),
        ('pickup_location_id', Int32),
        ('dropoff_location_id', Int32),
        ('payment_type', Int64),
        ('fare_amount', Float64),
        ('extra', Float64),
        ('mta_tax', Float64),
        ('tip_amount', Float64),
        ('tolls_amount', Float64),
        ('improvement_surcharge', Float64),
        ('total_amount', Float64),
        ('congestion_surcharge', Float64),
        ('airport_fee', Float64),
        ('cbd_congestion_fee', Float64),
        ('borough', String),
        ('zone', String),
        ('service_zone', String),
        ('is_airport_pickup', Int8),
        ('duration_min', Float64),
        ('payment_type_str', String),
        ('rate_code_str', String),
        ('vendor_id_str', String),
        ('avg_speed_mph', Float64)])

In [98]:
df.describe()

shape: (9, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ vendor_id ┆ pickup_da ┆ dropoff_d ┆ … ┆ payment_t ┆ rate_code ┆ vendor_id ┆ avg_spee │
│ ---       ┆ ---       ┆ tetime    ┆ atetime   ┆   ┆ ype_str   ┆ _str      ┆ _str      ┆ d_mph    │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.475226e ┆ 3475226   ┆ 3475226   ┆ … ┆ 3475226   ┆ 2935077   ┆ 3475226   ┆ 3.475226 │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ e6       │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 540149    ┆ 0         ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.785428  ┆ 2025-01-1 ┆ 2025-01-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ NaN      │
│           ┆           ┆ 7 11:02:5 ┆ 7 11:17:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 5.910964  ┆ 6.997901  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 0.426328  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ NaN      │
│ min       ┆ 1.0       ┆ 2024-12-3 ┆ 2024-12-1 ┆ … ┆ cash      ┆ group_rid ┆ Creative  ┆ -64368.0 │
│           ┆           ┆ 1         ┆ 8         ┆   ┆           ┆ e         ┆ Mobile    ┆          │
│           ┆           ┆ 20:47:55  ┆ 07:52:40  ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 25%       ┆ 2.0       ┆ 2025-01-1 ┆ 2025-01-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 7.2103   │
│           ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 07:59:01  ┆ 08:15:29  ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 2.0       ┆ 2025-01-1 ┆ 2025-01-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 9.520343 │
│           ┆           ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 15:41:34  ┆ 15:59:34  ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2.0       ┆ 2025-01-2 ┆ 2025-01-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ 12.94117 │
│           ┆           ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆           ┆ 19:34:06  ┆ 19:48:31  ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 7.0       ┆ 2025-02-0 ┆ 2025-02-0 ┆ … ┆ unknown   ┆ standard_ ┆ Myle Tech ┆ inf      │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆ rate      ┆ nologies  ┆          │
│           ┆           ┆ 00:00:44  ┆ 23:44:11  ┆   ┆           ┆           ┆ Inc       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [99]:
# Zero column analysis -- Clean up output, i.e. pivot column names to rows with one column "count"
cols = [
    "passenger_count",
    "trip_distance",
    "duration_min",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "airport_fee",
    "cbd_congestion_fee",
]
pl.concat(
    [df.select(pl.lit(c).alias("column"), (pl.col(c) == 0).sum().alias("zero_count")) for c in cols]
)

shape: (13, 2)
┌───────────────────────┬────────────┐
│ column                ┆ zero_count │
│ ---                   ┆ ---        │
│ str                   ┆ u32        │
╞═══════════════════════╪════════════╡
│ passenger_count       ┆ 24656      │
│ trip_distance         ┆ 90893      │
│ duration_min          ┆ 1927       │
│ fare_amount           ┆ 1398       │
│ extra                 ┆ 1764424    │
│ mta_tax               ┆ 38170      │
│ tip_amount            ┆ 1118008    │
│ tolls_amount          ┆ 3259590    │
│ improvement_surcharge ┆ 37694      │
│ total_amount          ┆ 559        │
│ congestion_surcharge  ┆ 225938     │
│ airport_fee           ┆ 2706446    │
│ cbd_congestion_fee    ┆ 1222178    │
└───────────────────────┴────────────┘

In [100]:
# Tail analysis
cols = ["trip_distance", "passenger_count", "duration_min"]
cast_df = df.with_columns(pl.col(cols).cast(pl.Float64))
pl.concat(
    [
        cast_df.select(
            pl.lit(c).alias("column"),
            pl.col(c).min().alias("min"),
            pl.col(c).quantile(0.001).alias("p0.1"),
            pl.col(c).quantile(0.999).alias("p99.9"),
            pl.col(c).max().alias("max"),
        )
        for c in cols
    ]
)

shape: (3, 5)
┌─────────────────┬───────────────┬──────────┬───────────┬─────────────┐
│ column          ┆ min           ┆ p0.1     ┆ p99.9     ┆ max         │
│ ---             ┆ ---           ┆ ---      ┆ ---       ┆ ---         │
│ str             ┆ f64           ┆ f64      ┆ f64       ┆ f64         │
╞═════════════════╪═══════════════╪══════════╪═══════════╪═════════════╡
│ trip_distance   ┆ 0.0           ┆ 0.0      ┆ 28.86     ┆ 276423.57   │
│ passenger_count ┆ 0.0           ┆ 0.0      ┆ 6.0       ┆ 9.0         │
│ duration_min    ┆ -51472.316667 ┆ 0.066667 ┆ 98.266667 ┆ 5626.316667 │
└─────────────────┴───────────────┴──────────┴───────────┴─────────────┘

In [101]:
# Hour-by-hour distribution
df.group_by(pl.col("pickup_datetime").dt.hour().alias("hour")).agg(
    pl.col("duration_min").mean().alias("avg_duration")
).sort("hour")

shape: (24, 2)
┌──────┬──────────────┐
│ hour ┆ avg_duration │
│ ---  ┆ ---          │
│ i8   ┆ f64          │
╞══════╪══════════════╡
│ 0    ┆ 13.785256    │
│ 1    ┆ 12.06919     │
│ 2    ┆ 12.763833    │
│ 3    ┆ 12.500513    │
│ 4    ┆ 14.155369    │
│ 5    ┆ 15.998068    │
│ 6    ┆ 15.67766     │
│ 7    ┆ 15.709326    │
│ 8    ┆ 15.574044    │
│ 9    ┆ 15.055785    │
│ 10   ┆ 14.938037    │
│ 11   ┆ 15.339699    │
│ 12   ┆ 15.270587    │
│ 13   ┆ 15.653991    │
│ 14   ┆ 16.513955    │
│ 15   ┆ 16.724708    │
│ 16   ┆ 16.738171    │
│ 17   ┆ 15.856804    │
│ 18   ┆ 14.500614    │
│ 19   ┆ 13.991177    │
│ 20   ┆ 13.681685    │
│ 21   ┆ 13.842334    │
│ 22   ┆ 14.097557    │
│ 23   ┆ 14.025077    │
└──────┴──────────────┘

In [102]:
# Payment type distribution
df["payment_type"].value_counts()

shape: (6, 2)
┌──────────────┬─────────┐
│ payment_type ┆ count   │
│ ---          ┆ ---     │
│ i64          ┆ u32     │
╞══════════════╪═════════╡
│ 4            ┆ 76481   │
│ 5            ┆ 1       │
│ 2            ┆ 390429  │
│ 3            ┆ 23773   │
│ 0            ┆ 540149  │
│ 1            ┆ 2444393 │
└──────────────┴─────────┘

In [103]:
# Zone distribution
zone_counts = df["zone"].value_counts().sort("count", descending=True)
display(zone_counts)

shape: (260, 2)
┌─────────────────────────────────┬────────┐
│ zone                            ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Midtown Center                  ┆ 169977 │
│ Upper East Side South           ┆ 163703 │
│ Upper East Side North           ┆ 155647 │
│ JFK Airport                     ┆ 146137 │
│ Times Sq/Theatre District       ┆ 125829 │
│ Penn Station/Madison Sq West    ┆ 119131 │
│ Midtown East                    ┆ 117930 │
│ Lincoln Square East             ┆ 110585 │
│ Upper West Side South           ┆ 96614  │
│ Midtown North                   ┆ 95906  │
│ Union Sq                        ┆ 95896  │
│ Murray Hill                     ┆ 95636  │
│ …                               ┆ …      │
│ West Brighton                   ┆ 6      │
│ Breezy Point/Fort Tilden/Riis … ┆ 4      │
│ Great Kills                     ┆ 4      │
│ Charleston/Tottenville          ┆ 3      │
│ Arden Heights                   ┆ 3      │
│ Green-Wood Cemetery             ┆ 3      │
│ Rossville/Woodrow               ┆ 3      │
│ Oakwood                         ┆ 2      │
│ Port Richmond                   ┆ 2      │
│ Rikers Island                   ┆ 1      │
│ Eltingville/Annadale/Prince's … ┆ 1      │
│ Freshkills Park                 ┆ 1      │
└─────────────────────────────────┴────────┘

In [104]:
# Airport pickup distribution
df["is_airport_pickup"].value_counts()

shape: (2, 2)
┌───────────────────┬─────────┐
│ is_airport_pickup ┆ count   │
│ ---               ┆ ---     │
│ i8                ┆ u32     │
╞═══════════════════╪═════════╡
│ 0                 ┆ 3239054 │
│ 1                 ┆ 236172  │
└───────────────────┴─────────┘

In [105]:
# Borough pickup distribution
df["borough"].value_counts()

shape: (8, 2)
┌───────────────┬─────────┐
│ borough       ┆ count   │
│ ---           ┆ ---     │
│ str           ┆ u32     │
╞═══════════════╪═════════╡
│ EWR           ┆ 377     │
│ Unknown       ┆ 8141    │
│ Manhattan     ┆ 3089275 │
│ Bronx         ┆ 14741   │
│ Staten Island ┆ 256     │
│ Queens        ┆ 294986  │
│ N/A           ┆ 1380    │
│ Brooklyn      ┆ 66070   │
└───────────────┴─────────┘

In [106]:
# N/A Borough breakout
df.filter(df["borough"] == "N/A")["zone"].value_counts()

shape: (1, 2)
┌────────────────┬───────┐
│ zone           ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Outside of NYC ┆ 1380  │
└────────────────┴───────┘

In [107]:
df.filter((pl.col("fare_amount") == 0) & (pl.col("total_amount") == 0))

shape: (527, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ pickup_da ┆ dropoff_d ┆ passenger ┆ … ┆ payment_t ┆ rate_code ┆ vendor_id ┆ avg_spee │
│ ---       ┆ tetime    ┆ atetime   ┆ _count    ┆   ┆ ype_str   ┆ _str      ┆ _str      ┆ d_mph    │
│ i32       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ datetime[ ┆ datetime[ ┆ i64       ┆   ┆ str       ┆ str       ┆ str       ┆ f64      │
│           ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ cash      ┆ standard_ ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rate      ┆ Mobility, ┆          │
│           ┆ 01:30:13  ┆ 01:30:31  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ no_charge ┆ standard_ ┆ Creative  ┆ 4.721311 │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆          │
│           ┆ 03:57:21  ┆ 04:02:26  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ dispute   ┆ standard_ ┆ Creative  ┆ 12.88343 │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆ 6        │
│           ┆ 03:27:25  ┆ 03:43:43  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 2         ┆ … ┆ cash      ┆ standard_ ┆ Curb      ┆ 33.97183 │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rate      ┆ Mobility, ┆ 1        │
│           ┆ 04:03:25  ┆ 04:11:42  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 4         ┆ … ┆ cash      ┆ standard_ ┆ Curb      ┆ 20.50331 │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rate      ┆ Mobility, ┆ 1        │
│           ┆ 04:24:55  ┆ 04:29:57  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ cash      ┆ negotiate ┆ Creative  ┆ NaN      │
│           ┆ 2         ┆ 2         ┆           ┆   ┆           ┆ d_fare    ┆ Mobile    ┆          │
│           ┆ 01:48:11  ┆ 01:48:11  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ no_charge ┆ standard_ ┆ Creative  ┆ 0.0      │
│           ┆ 2         ┆ 2         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆          │
│           ┆ 07:05:37  ┆ 07:05:59  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ dispute   ┆ standard_ ┆ Creative  ┆ 0.0      │
│           ┆ 2         ┆ 2         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆          │
│           ┆ 07:39:50  ┆ 07:42:08  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ dispute   ┆ standard_ ┆ Creative  ┆ 0.0      │
│           ┆ 2         ┆ 2         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆          │
│           ┆ 07:48:54  ┆ 07:49:06  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ null_or_u ┆ Creative  ┆ 0.0      │
│           ┆ 2         ┆ 2         ┆           ┆   ┆ rd        ┆ nknown    ┆ Mobile    ┆          │
│           ┆ 08:48:38  ┆ 09:03:48  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ null_or_u ┆ Creative  ┆ 7.651154 │
│           ┆ 2         ┆ 2         ┆           ┆   ┆ rd        ┆ nknown    ┆ Mobile    ┆          │
│           ┆ 09:41:22  ┆ 10:26:51  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ dispute   ┆ standard_ ┆ Creative  ┆ 0.0      │
│           ┆ 2         ┆ 2         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆          │
│           ┆ 10:25:43  ┆ 10:26:36  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 1         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 8         ┆ 8         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 02:38:28  ┆ 02:40:39  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 0         ┆ 0         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 14:55:49  ┆ 15:25:09  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 2         ┆ 2         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 08:38:52  ┆ 09:00:00  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 9.863014 │
│           ┆ 3         ┆ 3         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 23:24:42  ┆ 23:33:13  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 7         ┆ 7         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 16:07:36  ┆ 16:10:09  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.434258 │
│           ┆ 8         ┆ 8         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 09:33:08  ┆ 09:46:57  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 13.13069 │
│           ┆ 8         ┆ 8         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆ 9        │
│           ┆ 21:39:36  ┆ 22:01:32  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 3.564356 │
│           ┆ 9         ┆ 9         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 08:48:50  ┆ 08:50:31  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 10.38895 │
│           ┆ 9         ┆ 9         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆ 9        │
│           ┆ 17:05:46  ┆ 17:19:03  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 9.067164 │
│           ┆ 0         ┆ 0         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 08:25:08  ┆ 08:43:00  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 18:09:52  ┆ 18:13:16  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 6.666667 │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 19:48:14  ┆ 19:53:38  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [108]:
df.filter((pl.col("trip_distance") == 0) & (pl.col("duration_min") > 1))

shape: (64_282, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ pickup_da ┆ dropoff_d ┆ passenger ┆ … ┆ payment_t ┆ rate_code ┆ vendor_id ┆ avg_spee │
│ ---       ┆ tetime    ┆ atetime   ┆ _count    ┆   ┆ ype_str   ┆ _str      ┆ _str      ┆ d_mph    │
│ i32       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ datetime[ ┆ datetime[ ┆ i64       ┆   ┆ str       ┆ str       ┆ str       ┆ f64      │
│           ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobile    ┆          │
│           ┆ 00:27:40  ┆ 00:59:30  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ negotiate ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ d_fare    ┆ Mobile    ┆          │
│           ┆ 00:43:22  ┆ 00:46:18  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ no_charge ┆ standard_ ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆          │
│           ┆ 00:14:57  ┆ 00:17:44  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ null_or_u ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ nknown    ┆ Mobile    ┆          │
│           ┆ 00:34:58  ┆ 01:09:03  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobile    ┆          │
│           ┆ 00:22:03  ┆ 00:24:00  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ null_or_u ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ nknown    ┆ Mobile    ┆          │
│           ┆ 00:37:13  ┆ 01:26:20  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 2         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 00:13:46  ┆ 00:29:45  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 2         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 00:32:18  ┆ 00:39:23  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 3         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 00:45:42  ┆ 01:23:00  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 3         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 00:39:18  ┆ 00:45:02  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ negotiate ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ d_fare    ┆ Mobile    ┆          │
│           ┆ 00:56:53  ┆ 00:58:12  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ null_or_u ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ rd        ┆ nknown    ┆ Mobile    ┆          │
│           ┆ 00:21:48  ┆ 00:54:50  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobility, ┆          │
│           ┆ 23:01:15  ┆ 23:15:12  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 23:44:05  ┆ 00:04:10  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobility, ┆          │
│           ┆ 23:57:46  ┆ 00:04:52  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobility, ┆          │
│           ┆ 23:27:37  ┆ 23:38:08  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobility, ┆          │
│           ┆ 23:45:34  ┆ 00:16:11  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 23:33:38  ┆ 23:50:43  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobility, ┆          │
│           ┆ 23:43:50  ┆ 23:51:14  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 23:55:55  ┆ 00:09:18  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 23:59:17  ┆ 00:03:43  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 23:17:38  ┆ 23:35:58  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Curb      ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobility, ┆          │
│           ┆ 23:39:25  ┆ 23:42:06  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ flex_fare ┆ null      ┆ Creative  ┆ 0.0      │
│           ┆ 1         ┆ 1         ┆           ┆   ┆ _trip     ┆           ┆ Mobile    ┆          │
│           ┆ 23:10:25  ┆ 23:36:21  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# Cleaning Calls!

keep_list = [
    "vendor_id",
    "pickup_datetime",
    "passenger_count",
    "store_and_fwd_flag",
    "pickup_location_id",
    "borough",
    "is_airport_pickup",
    "trip_distance",
    "duration_min",
    "avg_speed_mph",
]
df = df.drop_nulls(subset=keep_list)
df = df.filter(
    pl.col("duration_min") > 1,
    pl.col("trip_distance") > 0,
    pl.col("pickup_datetime").is_between(pl.date(2025, 1, 5), pl.date(2025, 1, 31)),
    pl.col("total_amount") > 0,
    pl.col("passenger_count") <= 6.0,
    pl.col("avg_speed_mph").is_between(1, 85),
)

df.select(keep_list)

shape: (2_406_716, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ pickup_da ┆ passenger ┆ store_and ┆ … ┆ is_airpor ┆ trip_dist ┆ duration_ ┆ avg_spee │
│ ---       ┆ tetime    ┆ _count    ┆ _fwd_flag ┆   ┆ t_pickup  ┆ ance      ┆ min       ┆ d_mph    │
│ i32       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ datetime[ ┆ i64       ┆ i64       ┆   ┆ i8        ┆ f64       ┆ f64       ┆ f64      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 1         ┆ 8.66      ┆ 17.75     ┆ 29.27323 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ 00:00:02  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 1         ┆ 9.73      ┆ 25.6      ┆ 22.80468 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│           ┆ 00:24:51  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 1         ┆ 10.33     ┆ 23.766667 ┆ 26.07854 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ 00:54:12  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2025-01-0 ┆ 0         ┆ 0         ┆ … ┆ 1         ┆ 10.3      ┆ 16.633333 ┆ 37.15430 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ 00:27:27  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 1.71      ┆ 5.733333  ┆ 17.89534 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ 00:10:19  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 1.8       ┆ 7.65      ┆ 14.11764 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│           ┆ 00:29:32  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 3.05      ┆ 14.45     ┆ 12.66436 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:06:01  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 5.81      ┆ 15.816667 ┆ 22.04004 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│           ┆ 00:48:01  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 1         ┆ 9.0       ┆ 20.733333 ┆ 26.04501 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆ 00:22:44  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 2.0       ┆ 8.966667  ┆ 13.3829  │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:52:47  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-0 ┆ 2         ┆ 0         ┆ … ┆ 0         ┆ 1.53      ┆ 7.616667  ┆ 12.05251 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆ 00:08:27  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-0 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 0.83      ┆ 3.566667  ┆ 13.96261 │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│           ┆ 00:21:27  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 0.74      ┆ 5.766667  ┆ 7.699422 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:45:27  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 2.71      ┆ 14.683333 ┆ 11.07378 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:58:24  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 2         ┆ 0         ┆ … ┆ 0         ┆ 2.4       ┆ 16.733333 ┆ 8.605578 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:56:18  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 6         ┆ 0         ┆ … ┆ 0         ┆ 4.52      ┆ 19.466667 ┆ 13.93150 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│           ┆ 23:59:52  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 2.31      ┆ 10.816667 ┆ 12.81355 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ 23:51:16  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 2.43      ┆ 13.366667 ┆ 10.90773 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ 23:57:31  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 4.04      ┆ 15.333333 ┆ 15.80869 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│           ┆ 23:58:02  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 5         ┆ 0         ┆ … ┆ 0         ┆ 2.05      ┆ 14.3      ┆ 8.601399 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:54:13  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 1         ┆ 8.93      ┆ 18.15     ┆ 29.52066 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│           ┆ 23:59:45  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 2.6       ┆ 14.716667 ┆ 10.60022 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│           ┆ 22:21:44  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 4.13      ┆ 15.95     ┆ 15.53605 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:44:28  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2025-01-3 ┆ 1         ┆ 0         ┆ … ┆ 0         ┆ 3.4       ┆ 17.183333 ┆ 11.87196 │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆ 23:38:42  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [110]:
# one-hot encode boroughs column
clean_df = df.to_dummies("borough")
clean_df.columns = [col.lower() for col in clean_df.columns]
del df
display(clean_df)

shape: (2_406_716, 36)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ pickup_da ┆ dropoff_d ┆ passenger ┆ … ┆ payment_t ┆ rate_code ┆ vendor_id ┆ avg_spee │
│ ---       ┆ tetime    ┆ atetime   ┆ _count    ┆   ┆ ype_str   ┆ _str      ┆ _str      ┆ d_mph    │
│ i32       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ datetime[ ┆ datetime[ ┆ i64       ┆   ┆ str       ┆ str       ┆ str       ┆ f64      │
│           ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 29.27323 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 9        │
│           ┆ 00:00:02  ┆ 00:17:47  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 22.80468 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 8        │
│           ┆ 00:24:51  ┆ 00:50:27  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 26.07854 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 1        │
│           ┆ 00:54:12  ┆ 01:17:58  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 0         ┆ … ┆ cash      ┆ standard_ ┆ Creative  ┆ 37.15430 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆ 9        │
│           ┆ 00:27:27  ┆ 00:44:05  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 17.89534 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 9        │
│           ┆ 00:10:19  ┆ 00:16:03  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 14.11764 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 7        │
│           ┆ 00:29:32  ┆ 00:37:11  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 12.66436 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 00:06:01  ┆ 00:20:28  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 22.04004 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 2        │
│           ┆ 00:48:01  ┆ 01:03:50  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ cash      ┆ standard_ ┆ Creative  ┆ 26.04501 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆           ┆ rate      ┆ Mobile    ┆ 6        │
│           ┆ 00:22:44  ┆ 00:43:28  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Creative  ┆ 13.3829  │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobile    ┆          │
│           ┆ 00:52:47  ┆ 01:01:45  ┆           ┆   ┆           ┆           ┆ Technolog ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ies L…    ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 2         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 12.05251 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 6        │
│           ┆ 00:08:27  ┆ 00:16:04  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 13.96261 │
│           ┆ 5         ┆ 5         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 7        │
│           ┆ 00:21:27  ┆ 00:25:01  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 7.699422 │
│           ┆ 0         ┆ 0         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 23:45:27  ┆ 23:51:13  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 11.07378 │
│           ┆ 0         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 23:58:24  ┆ 00:13:05  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 2         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 8.605578 │
│           ┆ 0         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 23:56:18  ┆ 00:13:02  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 6         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 13.93150 │
│           ┆ 0         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 7        │
│           ┆ 23:59:52  ┆ 00:19:20  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 12.81355 │
│           ┆ 0         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 9        │
│           ┆ 23:51:16  ┆ 00:02:05  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 10.90773 │
│           ┆ 0         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 1        │
│           ┆ 23:57:31  ┆ 00:10:53  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 15.80869 │
│           ┆ 0         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 6        │
│           ┆ 23:58:02  ┆ 00:13:22  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 5         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 8.601399 │
│           ┆ 0         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 23:54:13  ┆ 00:08:31  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 29.52066 │
│           ┆ 0         ┆ 1         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 1        │
│           ┆ 23:59:45  ┆ 00:17:54  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 10.60022 │
│           ┆ 0         ┆ 0         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 7        │
│           ┆ 22:21:44  ┆ 22:36:27  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 15.53605 │
│           ┆ 0         ┆ 0         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆          │
│           ┆ 22:44:28  ┆ 23:00:25  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ 1         ┆ … ┆ credit_ca ┆ standard_ ┆ Curb      ┆ 11.87196 │
│           ┆ 0         ┆ 0         ┆           ┆   ┆ rd        ┆ rate      ┆ Mobility, ┆ 9        │
│           ┆ 23:38:42  ┆ 23:55:53  ┆           ┆   ┆           ┆           ┆ LLC       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# EDA Notes

### Fields Known at Pickup:

- **VendorID** - I assume this has to be the taxi proprietor
- RatecodeID
- **tpep_pickup_datetime** - goes without saying
- **passenger_count** - again, you should know how many people are getting in the car
- **store_and_fwd_flag**(?) - not sure about this one
- **PULocationID** - again, you should know where you are
- **is_airport_ride** - Derived from PULocationID

### Pickup/Dropoff

- Earliest pickup datetime is after the earliest dropoff datetime
  - Going to need to remove records where:
    - tpep_dropoff_datetime <= tpep_pickup_datetime

### Zero Values

- **Trip Distance:** 90,893 zero distance records
- **Passenger Count:** 24,656 zero passenger records
- **Fare Amount:** 1,398 zero fare amount records (May or may not be legitimate)
  - Small population suggests that this is an error rather than legit zeros.
- **Total Amount:** 559 zero total amount records (May or may not be legitimate)
  - Small population suggests that this is an error rather than legit zeros.
  - _NOTE:_ Zero total amount population is smaller than zero fare amount population./nWarrants further investigation as this could be either:
    - The ride was actually free and the individual provided a tip or there was a categorical surcharge present
    - 559 of the 1,398 zero fare amount records should have a larger value present and the remainder were legitimate zero fare rides
- **Trip Duration:** Only 1,927 zero minute duration rides is vast difference from the 90,893 zero trip distance records
  - Could be cab starts meter after stopping for pickup and then ride is cancelled with time charged?
    - I don't live in NY, so I'm not sure how this works.

### Tail Analysis

- Trip distance has massive max error tail
  - p99.9 is only 28.86, so 276423.57 is both, per the dataset and mathematically, impossible
- Passenger count has only 18 records > 6.0 (four 7.0 records, eleven 8.0 records, and three 9.0 records)
  - Given there are millions of records, it seems wiser to just cut these out, although it is technically possible that there may have been babies present with parents or people sitting on laps illegally, just saying.
- Any negative trip duration/trip distance values can be removed from the dataset.

### Cross-Column Relationship Issues

- **Trip Duration x Trip Distance**
  - Potential problem in terms of its error tail. It's hard to say where the errors are and where some of them are just truly long trips when cross referenced with **Trip Distance.** There is a 91 mile trip where the meter ran for 5000+ minutes. Given that that is 3.5 days of usage, I doubt the time is entirely legitimate, but it is a long haul trip for sure. There are also hundreds where it ran for 300+ minutes on a 15-20 mile trip. So it's difficult to pin down where to actually remove meter errors and which are legitimate fares/trip durations.
  - Duration should have a minimum cutoff as well in relation to distance of some sort. Trips less than 1 minute seem ridiculous logically, but also, if something has a long distance then there needs to be a logical amount of trip duration for that distance.
  - _NOTE:_ Perhaps get trimmed, weighted average for time per mile travelled to determine a reasonable min/max for the cross-column relationship and remove anything that falls outside of that. I assume there are going to be accuracy issues as part of this. Could also create some sort of likelihood value of the mile/minute value and then filter based on that?
-